---
- hosts: {{hosts}}
  remote_user:  {{remote_user}}
  sudo: True
    tasks:
    - name: Install base packages
      apt: name=git state=present
      apt: name=htop state=present
      apt: name=rsync state=present
      apt: name=vim state=present
      apt: name=sysstat state=present
      apt: name=ansible state=present
