---
- hosts: '{{hosts}}'
  remote_user:  '{{user}}'
  become: True
  tasks:
    - name: Set sysstat program configuration
      copy: 
         src=template/sysstat/sysstat.conf
         dest=/etc/sysstat/sysstat
         owner=root group=root 
    - name: Set sysstat cron configuration
      copy: 
          src=template/sysstat/cron.d.sysstat
          dest=/etc/cron.d/sysstat
          owner=root group=root
    - name: Enable sysstat
      copy: 
          src=template/sysstat/default.sysstat
          dest=/etc/default/sysstat
          owner=root group=root
    - name: Install snmpd
      apt: name=snmpd state=present
    - name: Enable snmpd
      service: name=snmpd
               enabled=yes 
    - name: Start snmpd
      service: name=snmpd
               state=started
    - name: Install gpsd
      apt: 
        name: gpsd
        state: present
