---
- hosts: '{{hosts}}'
  remote_user: '{{user}}'
  become: True
  tasks:
    - name: Update cache
      apt: 
         update_cache: yes
    - name: Install bind9
      apt: 
         name: bind9 
         state: present
    - name: Install bind9utils
      apt: 
         name: bind9utils 
         state: present
    - name: Install openssl
      apt: 
         name: openssl 
         state: present
    - name: Install openvpn
      apt: 
         name: openvpn 
         state: present
    - name: Install olsrd
      apt: 
         name: olsrd 
         state: present
    - name: Install ansible
      apt: 
         name: ansible 
         state: present
    - name: Add DNS named.conf.local
      copy: 
         src: template/bind/named.conf.local
         dest: /etc/bind/named.conf.local
    - name: Update DNS Database
      template: 
         src: template/bind/db.pittmesh.j2
         dest: /etc/bind/db.pittmesh
    - name: Install database update cron job
      copy: 
         src: template/bind/cron.d.pmd
         dest: /etc/cron.d/pmd
         owner: root
         group: root
    - name: Enable ansible logging
      lineinfile: 
         dest: /etc/ansible/ansible.cfg
         regexp: "#log_path = /var/log/ansible.log"
         line: "log_path = /var/log/ansible.log" 
    - name: Enable ansible log rotation
      copy: 
         src: template/ansible/logrotate.d.ansible
         dest: /etc/logrotate.d/ansible
    - name: Use Localhost as resolver
      copy: 
         src: template/resolvconf/resolvconf.conf
         dest: /etc/resolvconf.conf
    - name: Update Resolver
      command: /sbin/resolvconf -u
    - name: Enable DNS Service
      service:
         name: bind9
         enabled: yes
         state: started
    - name: Restart Networking
      service: 
         name: networking
         state: restarted
